### ISSUE TITLE
Problems with test suite (yarn test)

### ISSUE THREAD

**Issue by NewEraCracker** [lynoapp/lib-jitsi-meet#21]
Since the migration to webpack from dist (see webpack.config.js), the test suite (yarn test) is broken. I'd appreciate if you could look into it.

However if you rollback to this version `4ff3651d1f9f7b5464a43d91ed7c7ea351bba5db`, the tests do work with 4 failures.
The fix for those failures is to change in `webpack-shared-config.js`:
```
        externals: {
            jquery: 'jquery'
        },
```
Replace with - and tests run fine:
```
        externals: {
            jquery: 'jQuery'
        },
```
Source: https://stackoverflow.com/a/34004313

This may be a breaking change, so proceed with care.

**Comment by sapkra** [comment]
I removed `externals` completely to match our README.
