### ISSUE TITLE
Incorrectly generated types/generated/modules/statistics/SpeakerStats.d.ts

### ISSUE THREAD

**Issue by NewEraCracker** [lynoapp/lib-jitsi-meet#22]
The file `types/generated/modules/statistics/SpeakerStats.d.ts` seems to be incorrectly generated due to an exports confusion.

To fix this, the line `module.exports = SpeakerStats;` has to be removed from `modules/statistics/SpeakerStats.ts` and the following changed in the same file: `class SpeakerStats {` to `export default class SpeakerStats {`.

I have not noticed any side-effects after performing this change.

**Comment by sapkra** [comment]
The generated types are not used. They are just there to notice new changes we need to apply to the hand-crafted types but I will have a look.

**Comment by sapkra** [comment]
Should be fixed in master.
