### ISSUE TITLE
Getting Babel Loader error after installing npm package

### ISSUE THREAD

**Issue by gautamjsingh** [lynoapp/lib-jitsi-meet#25]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Hi, 
First of all really appreciate the effort put by the team in getting this library out for folks trying to use lib-jitsi-meet. I was earlier using https://www.npmjs.com/package/@lyno/lib-jitsi-meet  to connect my app to my Jitsi Server [JVB] and it was working great. Recently I updated the JVB to new version as per recommendation by Jitsi team and the @lyno package stopped getting events from Jitsi server, so I looked at your @lyno package and saw that it has been deprecated with recommendation to use https://www.npmjs.com/package/@solyd/lib-jitsi-meet  package, which I did.  Now my application [ Written in ReactJS ] does not start and I get the following error at application start 

Uncaught Error: Module parse failed: Unexpected token (10:11)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|    * The object used for storage.
|    */
>   _storage = {};
|   /**
|    * Empties all keys out of the storage.

Above error is followed by this error

Uncaught ReferenceError: process is not defined 

Just to confirm, we never got these errors when using @lyno package 

## Current behavior
The  ReactJs application gives error when loading, the error started coming after we installed and started using @solyd/lib-jitsi-meet package 

## Expected Behavior
The application should work and receive events from JVB after successful connection 

## Possible Solution
---

## Steps to reproduce
npm i @solyd/lib-jitsi-meet 
Restart the application 
[I understand that the above steps are insufficient, but I can provide more details if required]

# Environment details
ReactJS applciation running on local server and connecting to beta.meet.jit.si

**Comment by gautamjsingh** [comment]
Apologies, but I realized, that this problem is not due to this npm package but other react issues.

**Comment by ketenburhan** [comment]
> Apologies, but I realized, that this problem is not due to this npm package but other react issues.

Can you share how did you overcome this situation? I have the exact same problem.

**Comment by ketenburhan** [comment]
> > Apologies, but I realized, that this problem is not due to this npm package but other react issues.
> 
> Can you share how did you overcome this situation? I have the exact same problem.

I have forked the repo (both the [solydhq/lib-jitsi-meet](https://github.com/solydhq/lib-jitsi-meet) and the [jitsi/js-utils](https://github.com/jitsi/js-utils)) and changed  `_storage = {}` to `constructor() { this._storage = {}; }`. And the problem solved

See. [@ketenburhan/lib-jitsi-meet](https://www.npmjs.com/package/@ketenburhan/lib-jitsi-meet) and [@ketenburhan/js-utils](https://www.npmjs.com/package/@ketenburhan/js-utils)
However, probably these packages never going to get updates, since I don't want to maintain the project.
