### ISSUE TITLE
Dont place enums in d.ts files

### ISSUE THREAD

**Issue by Fuzzyma** [lynoapp/lib-jitsi-meet#3]
Installing this repo via npm and using it in my projects leads to build failures because some of the enums are placed in d.ts files. Those files don't get transpiled into javascript and therefore the enums don't create the necessary javascript. Putting them in ts files would solve this issue

**Comment by sapkra** [comment]
You're right. I will have a look.

**Comment by sapkra** [comment]
Can you try the latest beta version `2.6726.1-beta.1`?

**Comment by sapkra** [comment]
My changes don't seem to work as indented. Reopened.

**Comment by sapkra** [comment]
I changed a few things in v2.6726.1-beta.3 which will improve the imports and will properly export the enums. Can you try it out? Once you approve it, I will publish it as stable.

**Comment by sapkra** [comment]
I tested it myself now. I found a bug, fixed it and published it as stable release.

**Comment by Fuzzyma** [comment]
I moved away from using the imported code and only used the types instead.
The reason was errors being thrown when importing the lib as esm module

**Comment by sapkra** [comment]
Is the esm error something we can fix or is it to deep in the jitsi lib?

**Comment by Fuzzyma** [comment]
I don't know. I once spent too much time on this already and didn't bother investigating
